# Generated by Django 5.2.17 on 2026-09-12 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('default_priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2')], default='P2', max_length=2)),
                ('default_sla_hours', models.PositiveIntegerField(default=24)),
                ('default_action', models.TextField(blank=True)),
                ('resolution_criteria', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2')], max_length=2)),
                ('technical_status', models.CharField(choices=[('OPEN', 'Problema presente'), ('RESOLVED', 'Resolução técnica confirmada')], default='OPEN', max_length=20)),
                ('workflow_status', models.CharField(choices=[('NEW', 'Novo'), ('TRIAGE', 'Triagem'), ('IN_PROGRESS', 'Em andamento'), ('WAITING_CUSTOMER', 'Aguardando cliente'), ('WAITING_THIRD_PARTY', 'Aguardando terceiro'), ('SCHEDULED', 'Agendado'), ('RESOLVED', 'Resolvido'), ('REOPENED', 'Reaberto'), ('DISMISSED', 'Descartado')], default='NEW', max_length=30)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_security_problems', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='customers.customer')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='inventory.endpoint')),
                ('problem_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problems', to='actionplan.problemtype')),
            ],
            options={
                'ordering': ['priority', '-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='actionplan.problem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['customer', 'technical_status'], name='actionplan__custome_8fb3ae_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['customer', 'workflow_status'], name='actionplan__custome_d7d674_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['customer', 'priority'], name='actionplan__custome_4605bf_idx'),
        ),
    ]
