# Generated by Django 5.2.17 on 2026-09-12 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ksc_key', models.CharField(max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('fqdn', models.CharField(blank=True, max_length=255)),
                ('windows_domain', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Aviso'), ('CRITICAL', 'Crítico'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=20)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('status_mask', models.BigIntegerField(blank=True, null=True)),
                ('agent_version', models.CharField(blank=True, max_length=120)),
                ('antivirus_version', models.CharField(blank=True, max_length=120)),
                ('antivirus_bases_at', models.DateTimeField(blank=True, null=True)),
                ('rtp_state', models.IntegerField(blank=True, null=True)),
                ('edr_status', models.IntegerField(blank=True, null=True)),
                ('last_visible_at', models.DateTimeField(blank=True, null=True)),
                ('last_agent_connection_at', models.DateTimeField(blank=True, null=True)),
                ('last_full_scan_at', models.DateTimeField(blank=True, null=True)),
                ('reboot_required', models.BooleanField(default=False)),
                ('virus_count', models.IntegerField(default=0)),
                ('uncured_count', models.IntegerField(default=0)),
                ('os_name', models.CharField(blank=True, max_length=255)),
                ('os_build', models.CharField(blank=True, max_length=80)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='customers.customer')),
            ],
            options={
                'ordering': ['hostname', 'display_name'],
                'indexes': [models.Index(fields=['customer', 'status'], name='inventory_e_custome_84ae52_idx'), models.Index(fields=['customer', 'hostname'], name='inventory_e_custome_798265_idx'), models.Index(fields=['customer', 'last_agent_connection_at'], name='inventory_e_custome_f680e2_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'ksc_key'), name='uq_endpoint_customer_ksc_key')],
            },
        ),
    ]
