# Generated by Django 5.2.17 on 2026-09-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Código')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ksc_host', models.CharField(max_length=255, verbose_name='Servidor KSC')),
                ('ksc_port', models.PositiveIntegerField(default=13299, verbose_name='Porta OpenAPI')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=80, verbose_name='Timezone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
