# Generated by Django 5.2.17 on 2026-09-12 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Executando'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falha')], default='RUNNING', max_length=20)),
                ('hosts_received', models.PositiveIntegerField(default=0)),
                ('endpoints_created', models.PositiveIntegerField(default=0)),
                ('endpoints_updated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='customers.customer')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
