# Generated by Django 5.2.17 on 2026-09-17 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WsusComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsus_id', models.CharField(max_length=120, verbose_name='ID WSUS')),
                ('hostname', models.CharField(max_length=255, verbose_name='Hostname')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('os_name', models.CharField(blank=True, max_length=255, verbose_name='Sistema operacional')),
                ('group_name', models.CharField(blank=True, max_length=255, verbose_name='Grupo WSUS')),
                ('update_state', models.CharField(choices=[('UPDATED', 'Atualizado'), ('PENDING', 'Pendente'), ('FAILED', 'Com falha'), ('REBOOT', 'Reboot pendente'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=20, verbose_name='Situação')),
                ('needed_count', models.PositiveIntegerField(default=0, verbose_name='Atualizações pendentes')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Atualizações com falha')),
                ('installed_count', models.PositiveIntegerField(default=0, verbose_name='Atualizações instaladas')),
                ('reboot_pending', models.BooleanField(default=False, verbose_name='Reboot pendente')),
                ('last_report_at', models.DateTimeField(blank=True, null=True, verbose_name='Último status report')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última coleta')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Computador WSUS',
                'verbose_name_plural': 'Computadores WSUS',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='WsusMaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('P0', 'P0 - Crítica'), ('P1', 'P1 - Alta'), ('P2', 'P2 - Operacional')], default='P2', max_length=2, verbose_name='Criticidade')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SCHEDULED', 'Agendado'), ('IN_PROGRESS', 'Em execução'), ('REBOOT', 'Aguardando reboot'), ('VALIDATION', 'Validação'), ('BLOCKED', 'Bloqueado'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=30, verbose_name='Status')),
                ('planned_start_at', models.DateTimeField(blank=True, null=True, verbose_name='Início previsto')),
                ('planned_end_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim previsto')),
                ('allow_reboot', models.BooleanField(default=False, verbose_name='Reboot permitido')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_wsus_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='wsus.wsuscomputer')),
            ],
            options={
                'verbose_name': 'Atividade WSUS',
                'verbose_name_plural': 'Atividades WSUS',
                'ordering': ['priority', 'planned_end_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WsusMaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wsus_events', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='wsus.wsusmaintenancetask')),
            ],
            options={
                'verbose_name': 'Evento WSUS',
                'verbose_name_plural': 'Eventos WSUS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WsusServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('hostname', models.CharField(max_length=255, verbose_name='Hostname')),
                ('port', models.PositiveIntegerField(default=8530, verbose_name='Porta')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Usa SSL')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última coleta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wsus_servers', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Servidor WSUS',
                'verbose_name_plural': 'Servidores WSUS',
                'ordering': ['customer__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='wsuscomputer',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='wsus.wsusserver'),
        ),
        migrations.AddConstraint(
            model_name='wsusserver',
            constraint=models.UniqueConstraint(fields=('customer', 'hostname'), name='uq_wsus_server_customer_hostname'),
        ),
        migrations.AddConstraint(
            model_name='wsuscomputer',
            constraint=models.UniqueConstraint(fields=('server', 'wsus_id'), name='uq_wsus_computer_server_id'),
        ),
    ]
